# Generated by Django 3.0.6 on 2020-05-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_room', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorDetail')),
                ('ward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.ward')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patient.detail')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorDetail')),
            ],
        ),
    ]
