# Generated by Django 3.0.6 on 2020-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='Hospital',
            new_name='ward_type',
        ),
    ]
